# Listen for incoming requrests
https_port 631 accel tls-cert=/etc/squid/ssl/ipp.crt tls-key=/etc/squid/ssl/ipp.key

cache_peer hazlitt.lan parent 631 0 no-query originserver name=ipp_server

# Access control lists (ACLs) to route traffic
acl all src all

# Unauthenticated for testing
# acl ipp_path urlpath_regex ^/ipp(/.*)?$ # Matches IPP requests (e.g. /ipp/print)
#  OR
# Authenticated for Power User, Home Hacking Party, Helping Your Neighbors in an Emergency, etc.
# "YYYYYYYYYY" and "ZZZZZZZZZZ" represent your secret authentication strings.
# Further '|' terms can be added to support multiple authentication strings
acl ipp_auth_path urlpath_regex ^/ipp/(YYYYYYYYYY|ZZZZZZZZZZ)(/.*)?$

# Route requests to appropriate backend
cache_peer_access ipp_server allow ipp_auth_path
cache_peer_access ipp_server deny all

# Deny direct access to Squid (only allow reverse proxying)
http_access allow ipp_auth_path
http_access deny all

# Disable caching for dynamic content
# cache deny ipp_path
cache deny ipp_auth_path

# Logging
access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log

# Miscellaneous settings
visible_hostname ipp.marecrisium.third-party.xyz
forwarded_for off # Optionally hide client IP from backends
via off
