icecast:
  image: sebastiandanconia/icecast:latest
  volumes:
    # Optional, but useful for advanced configurations
    - /srv/docker/volumes/icecast/icecast.xml:/etc/icecast2/icecast.xml
    - logs:/var/log/icecast2
  environment:
    # Uses the host's $TZ variable, or defaults to UTC
    - TZ=${TZ:-UTC}
    - ICECAST_SOURCE_PASSWORD=changeme
    - ICECAST_ADMIN_PASSWORD=changeme
    - ICECAST_PASSWORD=changeme
    - ICECAST_RELAY_PASSWORD=changeme
  ports:
    - 8000:8000
